### ISSUE TITLE
Remove the gallery from events page

### ISSUE THREAD

**Issue by adithya-s-k** [Shunya-PES/Shunya#8]
### **Remove the gallery from the events page**

🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.

📍 Follow the Guidelines to Contribute to the Project !!

---

✅ To be Mentioned while taking the issue :

Full name :
GitHub Profile Link :
Email ID :
Approach for this problem:

Happy Contributing 🚀

All the best.

**Comment by adithya-s-k** [comment]
@SarthakSKumar 
@karthik2603-theBrogrammer 
@its-abhishek 
@AnirudhRevanur 
@asphytheghoul 
@noughtsamar 
@ananyav24 

Take a look into this issue

**Comment by noughtsamar** [comment]
**Hi! I would like to work on this issue.
Full name : Samar Pratap
GitHub Profile Link : https://github.com/noughtsamar
Email ID : samarpratapald27@gmail.com**
Approach for this problem: 
Here, we might need our gallery later so removing it completely doesn't seem like the right solution. So, I've set 'display:none' for the gallery classes.
The resulting page looks something like this:
<img width="960" alt="Screenshot 2022-09-01 012549" src="https://user-images.githubusercontent.com/92373593/187770657-ae969fc5-2e79-428a-98b7-9ca56eb17cbe.png">

in order to fix the extra space that this generates when viewing on smaller screens, I have changed the height of the event class to 100%  in the media query section so that it occupies the entirety of the space provided. The result is something like this:
<img width="451" alt="Screenshot 2022-09-01 012702" src="https://user-images.githubusercontent.com/92373593/187771298-dcd3edfc-01be-4ebe-bd1f-be89a5fe5b25.png">

Kindly assign the issue to me if the solution seems apt. suggestions and/or corrections would be greatly appreciated.

**Comment by its-abhishek** [comment]
Full name :  Abhishek
GitHub Profile Link  :https://github.com/its-abhishek
Email ID : abhihonnapure@gmail.com
Approach for this problem: just I will comment out the div class (event-gallery) and when we needed the gallery  pages for showcase our event photos that just we have uncomment the same div tags.

after this our site looks: 
![sh](https://user-images.githubusercontent.com/100339461/187773613-ac61606b-23f5-40bb-9279-eb7fc0df3ecf.png)

**Comment by adithya-s-k** [comment]
we are removing the gallery for the following reasons
- It is using JS for now and the images will be loaded when the page loads and it will decrease loading time
- we are planning to integrate it with a backend serve as we have a lot of images to display
@noughtsamar @its-abhishek 

also fix the padding issue with the footer when you create the pull request

**Comment by akash-kamalesh** [comment]
Fixing issue #10 
Full name : Akash Kamalesh 
GitHub Profile Link : https://github.com/asphytheghoul
Email ID : akash.kamalesh03@gmail.com
Approach for this problem: In the media query section , changed the viewport height of the events section for 468px and above desktop width sizes, also added a new condition in the media query for 500px and below as it was not rendering properly otherwise, changed display to flex for the footer logo area and also updated the layout of the footer section when viewed on a phone to a more meaningful look. Applied flex styling to the footer for 500px and 700px view sizes and set the direction to column to render the footer titles in a more appealing way when viewed from mobile phones.
The gallery section has been commented out and the height of each section has been reduced.

Please assign this issue to me  

## Footer section for phones new look

![img5](https://user-images.githubusercontent.com/91832216/187925558-f1ed7226-b356-4313-9635-683cf89a13ca.png) <br/>

## Removed gap between events

![img4](https://user-images.githubusercontent.com/91832216/187925570-87cf83d8-8b12-44af-8780-57cbced92a37.png)
<br/>

## Width above 900px

![img3](https://user-images.githubusercontent.com/91832216/187925573-58f1113e-b675-4433-b80d-d0dfc3f640c4.png)
<br/>

## Width above 1536px

![img2](https://user-images.githubusercontent.com/91832216/187925576-579161fc-eb98-4791-af41-0f4d7f0b9f10.png)
<br/>

## Full window size view

![img1](https://user-images.githubusercontent.com/91832216/187925577-6131ddd9-6f8f-4b8d-b1c5-279dbdf7ead3.png)
<br/>
